version: '3.8'

services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: pedro
      MYSQL_DATABASE: vegaburguer
      MYSQL_USER: pedro
      MYSQL_PASSWORD: pedro
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"